

AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an EC2 instance using default vpc and subnetid

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.nano

  ImageId:
    Type: String
    Default: ami-01a4f99c4ac11b03c
  
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: ap-south-1a
    AllowedValues:
      - ap-south-1a
      - ap-south-1b
      - ap-south-1c

  VpcId:
    Type: String
    Description: Default VPC id
    Default: vpc-0a18450f247e395c0

  SubnetId:
    Type: String
    Description: Subnet in which to launch an EC2
    Default: subnet-08e07ce1ae8d710c7


Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      
      AvailabilityZone: !Ref MyAvailabilityZone

      #without networkinterace
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      SubnetId: !Ref SubnetId

     #with Networkinterface
      #NetworkInterfaces:
       # - DeviceIndex: 0
         # AssociatePublicIpAddress: true
          #DeleteOnTermination: true
          #SubnetId: !Ref SubnetId
          #GroupSet:
           # - !Ref MySecurityGroup
          

      Tags:
        - Key: Name
          Value: Demoec2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: My SG with port 22 and 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'          
          ToPort: '8080'
          CidrIp: 0.0.0.0/0

    
      