
    
     

AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName


  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.nano

  ImageId:
    Type: String
    Default: ami-01a4f99c4ac11b03c
  
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: ap-south-1a
    AllowedValues:
      - ap-south-1a
      - ap-south-1b
      - ap-south-1c

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone

      Tags:
        - Key: Name
          Value: Demoec2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My SG with port 22, and 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'          
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
